services:
  valkey:
    image: valkey:8.0-alpine
    container_name: aetherlay-valkey-preprod
    ports:
      - "6379:6379"
    volumes:
      - ./.valkey-data:/data
      - ./.valkey.conf:/usr/local/etc/valkey/valkey.conf
    command: valkey-server /usr/local/etc/valkey/valkey.conf --requirepass SOME_PASS

  redisinsight:
    image: redis/redisinsight:latest
    container_name: aetherlay-redisinsight-preprod
    ports:
      - "5540:5540"
    volumes:
      - ./.redisinsight:/data
    depends_on:
      - valkey

  aetherlay-hc:
    platform: linux/amd64
    image: ghcr.io/project-aethermesh/aetherlay/aetherlay-hc:preprod
    container_name: aetherlay-hc-preprod
    volumes:
      - ../configs:/configs:ro
    environment:
      - LOG_LEVEL=debug
      - VALKEY_HOST=aetherlay-valkey-preprod
      - VALKEY_PASS=SOME_PASS
    depends_on:
      - valkey

  aetherlay-lb:
    platform: linux/amd64
    image: ghcr.io/project-aethermesh/aetherlay/aetherlay-lb:preprod
    container_name: aetherlay-lb-preprod
    ports:
      - "8080:8080"
    volumes:
      - ../configs:/configs:ro
    environment:
      - LOG_LEVEL=debug
      - VALKEY_HOST=aetherlay-valkey-preprod
      - VALKEY_PASS=SOME_PASS
    depends_on:
      - aetherlay-hc
